name: Build(2.0.1_py3.8.17_cuda11.7.1_devel_ubuntu20.04)

env:
  BASE_IMAGE: "nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04"

  PYTHON_VERSION: "3.8.17"

  PYTORCH_VERSION: "2.0.1"
  PYTORCH_VERSION_SUFFIX: "+cu117"
  TORCHVISION_VERSION: "0.15.2"
  TORCHVISION_VERSION_SUFFIX: "+cu117"
  TORCHAUDIO_VERSION: "2.0.2"
  TORCHAUDIO_VERSION_SUFFIX: "+cu117"
  PYTORCH_DOWNLOAD_URL: "https://download.pytorch.org/whl/cu117/torch_stable.html"

  IMAGE_TAG: "2.0.1-py3.8.17-cuda11.7.1-devel-ubuntu20.04"

on:
  push:
    branches:
      - main
    paths:
      - 'docker/ubuntu/**'
      - '.github/workflows/docker_build_2.0.1_py3.8.17_cuda11.7.1_devel_ubuntu20.04.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login DockerHub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker/ubuntu/build.sh

      - name: Push docker image
        run: docker push cnstark/pytorch:${IMAGE_TAG}
