name: Build(1.10.0_py3.9.12_cuda11.1.1_devel_ubuntu20.04)

env:
  BASE_IMAGE: "nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04"

  PYTHON_VERSION: "3.9.12"

  PYTORCH_VERSION: "1.10.0"
  PYTORCH_VERSION_SUFFIX: "+cu111"
  TORCHVISION_VERSION: "0.11.0"
  TORCHVISION_VERSION_SUFFIX: "+cu111"
  TORCHAUDIO_VERSION: "0.10.0"
  TORCHAUDIO_VERSION_SUFFIX: "+cu111"
  PYTORCH_DOWNLOAD_URL: "https://download.pytorch.org/whl/torch_stable.html"

  IMAGE_TAG: "1.10.0-py3.9.12-cuda11.1.1-devel-ubuntu20.04"

on:
  push:
    branches:
      - main
    paths:
      - 'docker/ubuntu/**'
      - '.github/workflows/docker_build_1.10.0_py3.9.12_cuda11.1.1_devel_ubuntu20.04.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login DockerHub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker/ubuntu/build.sh

      - name: Push docker image
        run: docker push cnstark/pytorch:${IMAGE_TAG}
