name: Build(2.4.1_py3.10.15_cuda12.1.0_ubuntu22.04)

env:
  BASE_IMAGE: "ubuntu:22.04"

  PYTHON_VERSION: "3.10.15"

  PYTORCH_VERSION: "2.4.1"
  PYTORCH_VERSION_SUFFIX: "+cu121"
  TORCHVISION_VERSION: "0.19.1"
  TORCHVISION_VERSION_SUFFIX: "+cu121"
  TORCHAUDIO_VERSION: "2.4.1"
  TORCHAUDIO_VERSION_SUFFIX: "+cu121"
  PYTORCH_DOWNLOAD_URL: "https://download.pytorch.org/whl/cu121/torch_stable.html"

  IMAGE_TAG: "2.4.1-py3.10.15-cuda12.1.0-ubuntu22.04"

on:
  push:
    branches:
      - main
    paths:
      - 'docker/ubuntu/**'
      - '.github/workflows/docker_build_2.4.1_py3.10.15_cuda12.1.0_ubuntu22.04.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login DockerHub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker/ubuntu/build.sh

      - name: Push docker image
        run: docker push cnstark/pytorch:${IMAGE_TAG}
