name: Build(1.7.0_py3.8.13_cuda11.0.3_ubuntu18.04)

env:
  BASE_IMAGE: "ubuntu:18.04"

  PYTHON_VERSION: "3.8.13"

  PYTORCH_VERSION: "1.7.0"
  PYTORCH_VERSION_SUFFIX: "+cu110"
  TORCHVISION_VERSION: "0.8.1"
  TORCHVISION_VERSION_SUFFIX: "+cu110"
  TORCHAUDIO_VERSION: "0.7.0"
  TORCHAUDIO_VERSION_SUFFIX: ""
  PYTORCH_DOWNLOAD_URL: "https://download.pytorch.org/whl/torch_stable.html"

  IMAGE_TAG: "1.7.0-py3.8.13-cuda11.0.3-ubuntu18.04"

on:
  push:
    branches:
      - main
    paths:
      - 'docker/ubuntu/**'
      - '.github/workflows/docker_build_1.7.0_py3.8.13_cuda11.0.3_ubuntu18.04.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login DockerHub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker/ubuntu/build.sh

      - name: Push docker image
        run: docker push cnstark/pytorch:${IMAGE_TAG}
