name: Build(1.12.1_py3.9.12_cuda11.6.2_devel_ubuntu20.04)

env:
  BASE_IMAGE: "nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04"

  PYTHON_VERSION: "3.9.12"

  PYTORCH_VERSION: "1.12.1"
  PYTORCH_VERSION_SUFFIX: "+cu116"
  TORCHVISION_VERSION: "0.13.1"
  TORCHVISION_VERSION_SUFFIX: "+cu116"
  TORCHAUDIO_VERSION: "0.12.1"
  TORCHAUDIO_VERSION_SUFFIX: "+cu116"
  PYTORCH_DOWNLOAD_URL: "https://download.pytorch.org/whl/cu116/torch_stable.html"

  IMAGE_TAG: "1.12.1-py3.9.12-cuda11.6.2-devel-ubuntu20.04"

on:
  push:
    branches:
      - main
    paths:
      - 'docker/ubuntu/**'
      - '.github/workflows/docker_build_1.12.1_py3.9.12_cuda11.6.2_devel_ubuntu20.04.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login DockerHub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker/ubuntu/build.sh

      - name: Push docker image
        run: docker push cnstark/pytorch:${IMAGE_TAG}
